# Checkout code on every commit to the main branch
# Path: .github/workflows/run.yaml
name: Run Challenge Answers
on:
  push:
    tags:
      - '*'

jobs:
  run-answers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute challenge answer scripts
        run: |
          make seed
          DEBUG=1 make run | tee /tmp/answers.log
          echo "----------------------------------------"
          DEBUG=0 make run | tee /tmp/answers.txt

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          allowUpdates: true
          artifacts: "/tmp/answers.*"